[package]
name = "gb_emu"
version = "0.1.0"
authors = ["George Roger <georger@xmos.com>"]

[dependencies]
lazy_static = "1.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
png_encode_mini = "0.1.2"
